spring:
  profiles:
    active: @profileActive@
test:
  main: 'classpath疸그pplication.yml'
  dev: 'classpath疸그pplication.yml'
  fileMain: 'classpath疸그pplication.yml'
  fileDev: 'classpath疸그pplication.yml'
server:
  port: 9911
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
  log-name: package-study
  log-path: logs