spring:
  datasource:
    # \u65F6\u533A\u914D\u7F6E serverTimezone=GMT%2B8 \u4E1C\u516B\u533A
    url: jdbc:mysql://localhost:3306/study_mysql?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&waitTimeout=10
    username: root1
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validation-query: select 1
      filters: slf4j
      # \u914D\u7F6E\u521D\u59CB\u5316\u8FDE\u63A5\u6C60\uFF0C\u94FE\u63A5\u5931\u8D25\u62A5\u9519\u5173\u95ED\u94FE\u63A5
      initial-size: 5
      # \u914D\u7F6E\u6700\u5C0F\u94FE\u63A5
      min-idle: 5
      # \u914D\u7F6E\u6700\u5927\u8FDE\u63A5
      max-active: 5
      # \u914D\u7F6E\u83B7\u53D6\u94FE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
      max-wait: 60000
      useUnfairLock: true
      testWhileIdle: true
      test-on-borrow: false
      test-on-return: false
      # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      time-between-eviction-runs-millis: 60000
      # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      min-evictable-idle-time-millis: 300000
      filter:
        stat:
          slow-sql-millis: 50
          enabled: true
          log-slow-sql: true
logging:
  config: classpath:logback-spring.xml
  #  \u65E5\u5FD7\u683C\u5F0F${log-path}/${log-name}.log
  log-path: logs
  log-file: druid-study.log
  level:
    root: debug
    com.fly.druid: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # \u914D\u7F6E\u6570\u636E\u8868\u5B57\u6BB5\u6620\u5C04\u5230\u5B9E\u4F53\u7C7B
    mapUnderscoreToCamelCase: true
    # \u6307\u5B9AMybatis \u65E5\u5FD7\u7684\u5177\u4F53\u5B9E\u73B0
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl