jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
      limit: 200
      # 以毫秒为单位，指定多长时间没有访问，就让缓存失效
      expireAfterWriteInMillis: 200000
    hula:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 200
      # 以毫秒为单位，指定多长时间没有访问，就让缓存失效
      expireAfterWriteInMillis: 200000